/** Catalog of the 37 bodhipakkhiyā dhammā and related phenomena.
 *  Summaries are original study notes in essential form.
 *  Pali stock formulas are public-domain canonical phrasing.
 *  Sutta links point to SuttaCentral for full text and translations.
 */

export const APP = {
  title: "Nama-Rūpa Explorer",
  subtitle: "37 bodhipakkhiyā dhammā",
  mnemonic: "8 · 7 · 5 · 5 · 4 · 4 · 4",
  tagline: "Wings to awakening, grouped for study and cross-linked to Dhamma.",
};

export const SUTTAS = {
  dn16: {
    id: "dn16",
    ref: "DN 16",
    title: "Mahāparinibbāna Sutta",
    pali: "Mahāparinibbāna Sutta",
    sc: "https://suttacentral.net/dn16",
    note: "The Buddha's last days. The 37 are to be developed so that the holy life will last long for the welfare of many.",
  },
  dn22: {
    id: "dn22",
    ref: "DN 22",
    title: "Mahāsatipaṭṭhāna Sutta",
    pali: "Mahāsatipaṭṭhāna Sutta",
    sc: "https://suttacentral.net/dn22",
    note: "The longer discourse on the four establishments of mindfulness, including the four noble truths.",
  },
  dn29: {
    id: "dn29",
    ref: "DN 29",
    title: "Pāsādika Sutta",
    pali: "Pāsādika Sutta",
    sc: "https://suttacentral.net/dn29",
    note: "Lists the seven sets that make up the 37, as Dhamma well-proclaimed and to be recited in concord.",
  },
  mn10: {
    id: "mn10",
    ref: "MN 10",
    title: "Satipaṭṭhāna Sutta",
    pali: "Satipaṭṭhāna Sutta",
    sc: "https://suttacentral.net/mn10",
    note: "The direct path: body, feeling, mind, and dhammas, contemplating internally, externally, and both.",
  },
  mn77: {
    id: "mn77",
    ref: "MN 77",
    title: "Mahāsakuludāyi Sutta",
    pali: "Mahāsakuludāyi Sutta",
    sc: "https://suttacentral.net/mn77",
    note: "Gives the seven sets in full (MN 77.15–21) without yet using the later collective title.",
  },
  mn117: {
    id: "mn117",
    ref: "MN 117",
    title: "Mahācattārīsaka Sutta",
    pali: "Mahācattārīsaka Sutta",
    sc: "https://suttacentral.net/mn117",
    note: "The great forty: mundane and noble right view, and how right view leads the other path factors.",
  },
  mn118: {
    id: "mn118",
    ref: "MN 118",
    title: "Ānāpānasati Sutta",
    pali: "Ānāpānasati Sutta",
    sc: "https://suttacentral.net/mn118",
    note: "Sixteen steps of breath mindfulness fulfilling the four satipaṭṭhāna and the seven bojjhaṅga.",
  },
  mn141: {
    id: "mn141",
    ref: "MN 141",
    title: "Saccavibhaṅga Sutta",
    pali: "Saccavibhaṅga Sutta",
    sc: "https://suttacentral.net/mn141",
    note: "Analysis of the four noble truths, including definitions of each path factor.",
  },
  sn45_8: {
    id: "sn45_8",
    ref: "SN 45.8",
    title: "Vibhaṅga Sutta",
    pali: "Vibhaṅga Sutta",
    sc: "https://suttacentral.net/sn45.8",
    note: "The analysis of the noble eightfold path — the standard definitions of the eight factors.",
  },
  sn45_2: {
    id: "sn45_2",
    ref: "SN 45.2",
    title: "Upaḍḍha Sutta",
    pali: "Upaḍḍha Sutta",
    sc: "https://suttacentral.net/sn45.2",
    note: "Admirable friendship is the whole of the holy life, because it leads to the noble eightfold path.",
  },
  sn46_1: {
    id: "sn46_1",
    ref: "SN 46.1",
    title: "Himavanta Sutta",
    pali: "Himavanta Sutta",
    sc: "https://suttacentral.net/sn46.1",
    note: "As nāgas depend on the Himalaya, a bhikkhu depends on virtue, then develops the seven awakening factors.",
  },
  sn46_51: {
    id: "sn46_51",
    ref: "SN 46.51",
    title: "Āhāra Sutta",
    pali: "Āhāra Sutta",
    sc: "https://suttacentral.net/sn46.51",
    note: "Nutriment and denourishment of the five hindrances and of the seven bojjhaṅga.",
  },
  sn47_1: {
    id: "sn47_1",
    ref: "SN 47.1",
    title: "Ambapāli Sutta",
    pali: "Ambapāli Sutta",
    sc: "https://suttacentral.net/sn47.1",
    note: "This is the direct path for the purification of beings: the four establishments of mindfulness.",
  },
  sn47_35: {
    id: "sn47_35",
    ref: "SN 47.35",
    title: "Sata Sutta",
    pali: "Sata Sutta",
    sc: "https://suttacentral.net/sn47.35",
    note: "A bhikkhu should be mindful and clearly comprehending — definitions of sati and sampajañña.",
  },
  sn48_10: {
    id: "sn48_10",
    ref: "SN 48.10",
    title: "Dutiyavibhaṅga Sutta",
    pali: "Dutiyavibhaṅga Sutta",
    sc: "https://suttacentral.net/sn48.10",
    note: "Analysis of the five faculties: faith, energy, mindfulness, concentration, wisdom.",
  },
  sn48_43: {
    id: "sn48_43",
    ref: "SN 48.43",
    title: "Sāketa Sutta",
    pali: "Sāketa Sutta",
    sc: "https://suttacentral.net/sn48.43",
    note: "The five faculties and five powers are the same qualities, distinguished by the angle of view.",
  },
  sn49_1: {
    id: "sn49_1",
    ref: "SN 49.1",
    title: "Sammappadhāna Saṃyutta",
    pali: "Daṇḍa Sutta",
    sc: "https://suttacentral.net/sn49.1",
    note: "Opens the connected discourses on the four right strivings.",
  },
  sn50_1: {
    id: "sn50_1",
    ref: "SN 50.1",
    title: "Bala Saṃyutta",
    pali: "Daṇḍa Sutta",
    sc: "https://suttacentral.net/sn50.1",
    note: "Opens the connected discourses on the five powers.",
  },
  sn51_15: {
    id: "sn51_15",
    ref: "SN 51.15",
    title: "Uṇṇābhabrāhmaṇa Sutta",
    pali: "Uṇṇābhabrāhmaṇa Sutta",
    sc: "https://suttacentral.net/sn51.15",
    note: "Chanda is for the sake of abandoning craving; when the goal is reached, that desire subsides.",
  },
  sn51_20: {
    id: "sn51_20",
    ref: "SN 51.20",
    title: "Vibhaṅga Sutta",
    pali: "Vibhaṅga Sutta",
    sc: "https://suttacentral.net/sn51.20",
    note: "Analysis of the four bases of spiritual power, each with concentration and the formations of striving.",
  },
  sn56_11: {
    id: "sn56_11",
    ref: "SN 56.11",
    title: "Dhammacakkappavattana Sutta",
    pali: "Dhammacakkappavattana Sutta",
    sc: "https://suttacentral.net/sn56.11",
    note: "Setting in motion the wheel of Dhamma: the middle way as the noble eightfold path, and the four truths.",
  },
  an4_14: {
    id: "an4_14",
    ref: "AN 4.14",
    title: "Saṃvara Sutta",
    pali: "Saṃvara Sutta",
    sc: "https://suttacentral.net/an4.14",
    note: "The four strivings named restraint, abandoning, development, and protection.",
  },
  an4_276: {
    id: "an4_276",
    ref: "AN 4.276",
    title: "Iddhipāda",
    pali: "Iddhipāda Sutta",
    sc: "https://suttacentral.net/an4.276",
    note: "The four bases of power as a set for developing spiritual success.",
  },
  an5_2: {
    id: "an5_2",
    ref: "AN 5.2",
    title: "Vitthata Sutta",
    pali: "Vitthata Sutta",
    sc: "https://suttacentral.net/an5.2",
    note: "The five powers in detail, fulfilling stream-entry factors, right effort, satipaṭṭhāna, jhāna, and the truths.",
  },
  an8_19: {
    id: "an8_19",
    ref: "AN 8.19",
    title: "Pahārāda Sutta",
    pali: "Pahārāda Sutta",
    sc: "https://suttacentral.net/an8.19",
    note: "The ocean-simile discourse; among the wonders of the Dhamma is this complete training in the 37.",
  },
};

export const GROUPS = [
  {
    id: "magga",
    n: 8,
    order: 1,
    pali: "ariyo aṭṭhaṅgiko maggo",
    short: "maggaṅga",
    english: "Noble eightfold path",
    gloss: "The middle way as eight path factors.",
    essence:
      "The path itself: view, intention, speech, action, livelihood, effort, mindfulness, and concentration. The other six sets are this path seen as training, faculties, powers, and awakening factors.",
    canonicalOrder: 7,
    suttas: ["sn56_11", "sn45_8", "mn117", "mn141", "dn22"],
    formula: "ariyo aṭṭhaṅgiko maggo, seyyathidaṃ — sammā-diṭṭhi … sammā-samādhi",
    color: "gold",
  },
  {
    id: "bojjhanga",
    n: 7,
    order: 2,
    pali: "satta bojjhaṅgā",
    short: "bojjhaṅga",
    english: "Seven factors of awakening",
    gloss: "Qualities that lead to and constitute awakening.",
    essence:
      "Mindfulness investigates dhammas with energy. From that, rapture, tranquillity, concentration, and equanimity mature. Energizing factors (investigation, energy, rapture) and calming factors (tranquillity, concentration, equanimity) are balanced by sati.",
    canonicalOrder: 6,
    suttas: ["sn46_1", "sn46_51", "mn118", "mn77"],
    formula: "sati, dhammavicaya, viriya, pīti, passaddhi, samādhi, upekkhā",
    color: "amber",
  },
  {
    id: "indriya",
    n: 5,
    order: 3,
    pali: "pañcindriyāni",
    short: "indriya",
    english: "Five spiritual faculties",
    gloss: "Governing capacities that can be developed and balanced.",
    essence:
      "Faith, energy, mindfulness, concentration, and wisdom as faculties that take leadership in the mind. They are the same five qualities as the powers, seen as capacities still being trained.",
    canonicalOrder: 4,
    suttas: ["sn48_10", "sn48_43", "mn77"],
    formula: "saddhā, viriya, sati, samādhi, paññā",
    color: "moss",
  },
  {
    id: "bala",
    n: 5,
    order: 4,
    pali: "pañca balāni",
    short: "bala",
    english: "Five powers",
    gloss: "The same five faculties, unshakeable.",
    essence:
      "When the faculties cannot be overthrown by their opposites — doubt, laziness, confusion, restlessness, and ignorance — they are called powers. SN 48.43 says faculty and power are not different dhammas.",
    canonicalOrder: 5,
    suttas: ["sn50_1", "an5_2", "sn48_43", "mn77"],
    formula: "saddhā-bala, viriya-bala, sati-bala, samādhi-bala, paññā-bala",
    color: "teal",
  },
  {
    id: "satipatthana",
    n: 4,
    order: 5,
    pali: "cattāro satipaṭṭhānā",
    short: "satipaṭṭhāna",
    english: "Four establishments of mindfulness",
    gloss: "Where sati is established: body, feeling, mind, dhammas.",
    essence:
      "The direct path (ekāyano maggo). One dwells contemplating body, feeling, mind, and dhammas — ardent, clearly comprehending, mindful, having put away longing and discontent regarding the world.",
    canonicalOrder: 1,
    suttas: ["mn10", "dn22", "sn47_1", "sn47_35", "mn118"],
    formula: "kāye kāyānupassī viharati … vedanāsu … citte … dhammesu dhammānupassī",
    color: "clay",
  },
  {
    id: "padhana",
    n: 4,
    order: 6,
    pali: "cattāro sammappadhānā",
    short: "sammappadhāna",
    english: "Four right strivings",
    gloss: "The fourfold work of viriya.",
    essence:
      "Prevent unarisen unwholesome states, abandon those that have arisen, develop unarisen wholesome states, and maintain those that have arisen. This is right effort applied to the two sides of the path.",
    canonicalOrder: 2,
    suttas: ["an4_14", "sn49_1", "sn45_8", "mn141"],
    formula: "anuppannānaṃ akusalānaṃ anuppādāya … uppannānaṃ pahānāya … kusalānaṃ uppādāya … ṭhitiyā",
    color: "rust",
  },
  {
    id: "iddhipada",
    n: 4,
    order: 7,
    pali: "cattāro iddhipādā",
    short: "iddhipāda",
    english: "Four bases of spiritual power",
    gloss: "Concentration born of desire, energy, mind, and investigation.",
    essence:
      "Each base is concentration (samādhi) together with the volitional formations of striving (padhāna-saṅkhāra), founded on chanda, viriya, citta, or vīmaṃsā. Power here means success in the development of the mind.",
    canonicalOrder: 3,
    suttas: ["sn51_20", "sn51_15", "an4_276", "mn77"],
    formula: "chanda-samādhi-padhāna-saṅkhāra-samannāgata iddhipāda",
    color: "plum",
  },
];

export const THREADS = [
  {
    id: "sati",
    pali: "sati",
    english: "Mindfulness",
    essence:
      "Presence of mind that remembers the object and does not float away. As satipaṭṭhāna it has four fields; as a faculty, power, awakening factor, and path factor it is the same quality in different offices.",
  },
  {
    id: "viriya",
    pali: "viriya",
    english: "Energy",
    essence:
      "The four right strivings are viriya at work. It also appears as a base of power, a faculty, a power, an awakening factor, and as right effort on the path.",
  },
  {
    id: "samadhi",
    pali: "samādhi",
    english: "Concentration",
    essence:
      "Unification of mind. The iddhipāda are forms of samādhi with striving. It is a faculty, power, awakening factor, and the eighth path factor, often specified as the four jhānas.",
  },
  {
    id: "panna",
    pali: "paññā",
    english: "Wisdom",
    essence:
      "Seeing phenomena as they are. Right view, investigation of dhammas, the wisdom faculty and power, and vīmaṃsā as a base of power are this knowing in different strengths and tasks.",
  },
  {
    id: "saddha",
    pali: "saddhā",
    english: "Faith",
    essence:
      "Confidence in the Buddha, Dhamma, and Saṅgha that launches energy. As faculty it can still waver; as power it is not overthrown by doubt.",
  },
  {
    id: "sila",
    pali: "sīla",
    english: "Virtue",
    essence:
      "Right speech, action, and livelihood are the virtue aggregate of the path. They protect the mind so sati and samādhi can stand.",
  },
  {
    id: "samatha-vipassana",
    pali: "samatha–vipassanā",
    english: "Calm and insight",
    essence:
      "The 37 are not two paths. Calming factors (passaddhi, samādhi, upekkhā, jhāna) and seeing factors (dhammavicaya, paññā, dhammānupassanā) are cultivated together.",
  },
];

export const PHENOMENA = [
  {
    id: "avijja",
    pali: "avijjā",
    english: "Ignorance",
    kind: "nidana",
    essence: "Not knowing the four noble truths. The first link of dependent origination and the opposite of right view.",
    factors: ["samma-ditthi", "dhammavicaya", "pannindriya", "panna-bala"],
    related: ["sankhara", "dukkha", "samudaya"],
  },
  {
    id: "sankhara",
    pali: "saṅkhārā",
    english: "Volitional formations",
    kind: "nidana",
    essence: "Kamma-forming activities conditioned by ignorance. Also the fourth aggregate when named as a khandha.",
    factors: ["samma-sankappa", "samma-kammanta", "chanda"],
    related: ["avijja", "vinnana", "sankhara-khandha"],
  },
  {
    id: "vinnana",
    pali: "viññāṇa",
    english: "Consciousness",
    kind: "nidana",
    essence: "Knowing at a sense door. Conditioned by formations; it pairs with nāma-rūpa. Also the fifth aggregate.",
    factors: ["cittanupassana", "citta"],
    related: ["namarupa", "sankhara", "vinnana-khandha"],
  },
  {
    id: "namarupa",
    pali: "nāma-rūpa",
    english: "Name and form",
    kind: "nidana",
    essence: "Mentality-materiality: feeling, perception, intention, contact, attention together with the form taken up. The original explorer's theme.",
    factors: ["kayanupassana", "vedananupassana", "cittanupassana", "dhammanupassana"],
    related: ["vinnana", "salayatana", "rupa", "vedana-khandha"],
  },
  {
    id: "salayatana",
    pali: "saḷāyatana",
    english: "Six sense bases",
    kind: "nidana",
    essence: "Eye, ear, nose, tongue, body, and mind as meeting-places of experience.",
    factors: ["kayanupassana", "cittanupassana"],
    related: ["namarupa", "phassa"],
  },
  {
    id: "phassa",
    pali: "phassa",
    english: "Contact",
    kind: "nidana",
    essence: "The meeting of base, object, and consciousness. Condition for feeling.",
    factors: ["kayanupassana", "vedananupassana"],
    related: ["salayatana", "vedana"],
  },
  {
    id: "vedana",
    pali: "vedanā",
    english: "Feeling",
    kind: "nidana",
    essence: "Pleasant, painful, or neither. A link of origination, an aggregate, and a satipaṭṭhāna.",
    factors: ["vedananupassana", "samma-sati"],
    related: ["phassa", "tanha", "vedana-khandha"],
  },
  {
    id: "tanha",
    pali: "taṇhā",
    english: "Craving",
    kind: "nidana",
    essence: "The origin of dukkha: craving for sensuality, for being, and for non-being.",
    factors: ["samma-sankappa", "pahana", "samma-ditthi"],
    related: ["vedana", "upadana", "samudaya"],
  },
  {
    id: "upadana",
    pali: "upādāna",
    english: "Clinging",
    kind: "nidana",
    essence: "Grasping at sensuality, views, precepts-and-vows, and a doctrine of self.",
    factors: ["samma-ditthi", "dhammanupassana"],
    related: ["tanha", "bhava"],
  },
  {
    id: "bhava",
    pali: "bhava",
    english: "Becoming",
    kind: "nidana",
    essence: "The kammic process of coming-to-be in a realm of existence.",
    factors: ["samma-kammanta", "samma-ajiva"],
    related: ["upadana", "jati"],
  },
  {
    id: "jati",
    pali: "jāti",
    english: "Birth",
    kind: "nidana",
    essence: "The arising of the aggregates in a new existence.",
    factors: [],
    related: ["bhava", "jaramarana"],
  },
  {
    id: "jaramarana",
    pali: "jarāmaraṇa",
    english: "Aging and death",
    kind: "nidana",
    essence: "The mass of dukkha that follows birth. Contemplated to arouse urgency (saṃvega).",
    factors: ["samma-ditthi", "kayanupassana"],
    related: ["jati", "dukkha"],
  },
  {
    id: "rupa",
    pali: "rūpa",
    english: "Form aggregate",
    kind: "khandha",
    essence: "Materiality: the four great elements and derived form. The field of kāyānupassanā.",
    factors: ["kayanupassana"],
    related: ["namarupa", "vedana-khandha"],
  },
  {
    id: "vedana-khandha",
    pali: "vedanākkhandha",
    english: "Feeling aggregate",
    kind: "khandha",
    essence: "The same vedanā counted as a heap of clinging.",
    factors: ["vedananupassana"],
    related: ["vedana", "sanna"],
  },
  {
    id: "sanna",
    pali: "saññā",
    english: "Perception aggregate",
    kind: "khandha",
    essence: "The marking and recognition of objects. Distorted perception feeds craving.",
    factors: ["cittanupassana", "dhammanupassana"],
    related: ["vedana-khandha", "sankhara-khandha"],
  },
  {
    id: "sankhara-khandha",
    pali: "saṅkhārakkhandha",
    english: "Formations aggregate",
    kind: "khandha",
    essence: "Volitional and other mental factors other than feeling, perception, and consciousness.",
    factors: ["samma-sankappa", "dhammanupassana"],
    related: ["sankhara", "vinnana-khandha"],
  },
  {
    id: "vinnana-khandha",
    pali: "viññāṇakkhandha",
    english: "Consciousness aggregate",
    kind: "khandha",
    essence: "The knowing of an object, classified by the six doors.",
    factors: ["cittanupassana"],
    related: ["vinnana", "namarupa"],
  },
  {
    id: "dukkha",
    pali: "dukkha",
    english: "Suffering (first truth)",
    kind: "sacca",
    essence: "Birth, aging, death, and the five clinging-aggregates. To be fully known.",
    factors: ["samma-ditthi", "dhammanupassana"],
    related: ["samudaya", "khandha-set"],
  },
  {
    id: "samudaya",
    pali: "samudaya",
    english: "Origin (second truth)",
    kind: "sacca",
    essence: "Craving that leads to fresh becoming. To be abandoned.",
    factors: ["samma-ditthi", "pahana", "samma-sankappa"],
    related: ["tanha", "nirodha"],
  },
  {
    id: "nirodha",
    pali: "nirodha",
    english: "Cessation (third truth)",
    kind: "sacca",
    essence: "The remainderless fading and cessation of that same craving. To be realized.",
    factors: ["samma-ditthi", "upekkha", "samma-samadhi"],
    related: ["samudaya", "magga-sacca"],
  },
  {
    id: "magga-sacca",
    pali: "magga",
    english: "Path (fourth truth)",
    kind: "sacca",
    essence: "The noble eightfold path. To be developed. The 37 are this development in seven presentations.",
    factors: ["samma-ditthi", "samma-samadhi"],
    related: ["nirodha", "dukkha"],
  },
  {
    id: "anicca",
    pali: "anicca",
    english: "Impermanence",
    kind: "lakkhana",
    essence: "All conditioned phenomena arise and cease. Insight into anicca opens dukkha and anattā.",
    factors: ["dhammavicaya", "pannindriya", "dhammanupassana"],
    related: ["dukkha-lakkhana", "anatta"],
  },
  {
    id: "dukkha-lakkhana",
    pali: "dukkha",
    english: "Unsatisfactoriness",
    kind: "lakkhana",
    essence: "Because they change, formations cannot be a secure basis for happiness.",
    factors: ["samma-ditthi", "dhammanupassana"],
    related: ["anicca", "anatta"],
  },
  {
    id: "anatta",
    pali: "anattā",
    english: "Not-self",
    kind: "lakkhana",
    essence: "The five aggregates are not to be taken as 'I', 'mine', or 'myself'.",
    factors: ["cittanupassana", "dhammanupassana", "pannindriya"],
    related: ["anicca", "khandha-set"],
  },
  {
    id: "lobha",
    pali: "lobha",
    english: "Greed",
    kind: "root",
    essence: "The unwholesome root of attraction. Opposite of non-greed and of letting go.",
    factors: ["pahana", "samvara", "samma-sankappa"],
    related: ["dosa", "moha", "tanha"],
  },
  {
    id: "dosa",
    pali: "dosa",
    english: "Hate",
    kind: "root",
    essence: "The unwholesome root of aversion. Opposite of non-hate and of goodwill.",
    factors: ["pahana", "samvara", "samma-sankappa"],
    related: ["lobha", "moha"],
  },
  {
    id: "moha",
    pali: "moha",
    english: "Delusion",
    kind: "root",
    essence: "The unwholesome root of not-knowing. Overlap with avijjā as a mental root.",
    factors: ["samma-ditthi", "dhammavicaya", "pahana"],
    related: ["avijja", "lobha", "dosa"],
  },
  {
    id: "nivarana",
    pali: "nīvaraṇa",
    english: "Five hindrances",
    kind: "dhamma",
    essence: "Sensual desire, ill will, sloth-and-torpor, restlessness-and-worry, and doubt. Contemplated under dhammas; they starve the bojjhaṅga.",
    factors: ["dhammanupassana", "samvara", "pahana", "sati-sambojjhanga"],
    related: ["moha", "jhana"],
  },
  {
    id: "jhana",
    pali: "jhāna",
    english: "Absorption",
    kind: "dhamma",
    essence: "The four jhānas are the usual definition of right concentration, and the fulfilment of the concentration power.",
    factors: ["samma-samadhi", "samadhindriya", "samadhi-bala", "samadhi-sambojjhanga"],
    related: ["nivarana"],
  },
  {
    id: "khandha-set",
    pali: "pañcakkhandhā",
    english: "Five aggregates",
    kind: "khandha",
    essence: "Form, feeling, perception, formations, consciousness — the field of clinging and of insight.",
    factors: ["dhammanupassana", "samma-ditthi"],
    related: ["rupa", "vedana-khandha", "sanna", "sankhara-khandha", "vinnana-khandha"],
  },
  {
    id: "micchaditthi",
    pali: "micchā-diṭṭhi",
    english: "Wrong view",
    kind: "path-opposite",
    essence: "The opposite of right view. Ignorance given the shape of a doctrine.",
    factors: ["samma-ditthi"],
    related: ["avijja", "upadana"],
  },
];

const F = (row) => row;

export const FACTORS = [
  F({
    id: "samma-ditthi",
    group: "magga",
    n: 1,
    pali: "sammā-diṭṭhi",
    english: "Right view",
    threads: ["panna", "samatha-vipassana"],
    phenomena: ["dukkha", "samudaya", "nirodha", "magga-sacca", "avijja", "micchaditthi"],
    sameAs: ["dhammavicaya", "pannindriya", "panna-bala", "vimamsa"],
    suttas: ["sn45_8", "sn56_11", "mn117", "mn141"],
    formula: "dukkhe ñāṇaṃ, dukkhasamudaye ñāṇaṃ, dukkhanirodhe ñāṇaṃ, dukkhanirodhagāminiyā paṭipadāya ñāṇaṃ",
    essence:
      "Knowledge of the four noble truths. Mundane right view understands kamma and results; noble right view is the path-factor that sees the truths directly.",
    practice: "Name dukkha, its origin, its cessation, and the path in whatever is occurring — especially feeling and craving.",
  }),
  F({
    id: "samma-sankappa",
    group: "magga",
    n: 2,
    pali: "sammā-saṅkappa",
    english: "Right intention",
    threads: ["panna", "sila"],
    phenomena: ["tanha", "lobha", "dosa", "sankhara"],
    sameAs: [],
    suttas: ["sn45_8", "mn141", "mn117"],
    formula: "nekkhamma-saṅkappa, abyāpāda-saṅkappa, avihiṃsā-saṅkappa",
    essence:
      "Intentions of renunciation, non-ill-will, and non-cruelty. Thought aligned with right view, turning away from greed and harm.",
    practice: "When a thought of sensuality, ill will, or cruelty arises, replace it with letting-go, goodwill, or compassion.",
  }),
  F({
    id: "samma-vaca",
    group: "magga",
    n: 3,
    pali: "sammā-vācā",
    english: "Right speech",
    threads: ["sila"],
    phenomena: ["bhava"],
    sameAs: [],
    suttas: ["sn45_8", "mn141"],
    formula: "musāvādā veramaṇī, pisuṇāya vācāya veramaṇī, pharusāya vācāya veramaṇī, samphappalāpā veramaṇī",
    essence:
      "Abstaining from false, divisive, harsh, and idle speech. Virtue that protects both others and one's own mind.",
    practice: "Before speaking, know whether it is true, beneficial, and timely.",
  }),
  F({
    id: "samma-kammanta",
    group: "magga",
    n: 4,
    pali: "sammā-kammanta",
    english: "Right action",
    threads: ["sila"],
    phenomena: ["bhava", "sankhara"],
    sameAs: [],
    suttas: ["sn45_8", "mn141"],
    formula: "pāṇātipātā veramaṇī, adinnādānā veramaṇī, kāmesu micchācārā veramaṇī",
    essence:
      "Abstaining from killing, taking what is not given, and sexual misconduct. Bodily kamma aligned with harmlessness.",
    practice: "Keep the bodily precepts as a field in which sati can grow.",
  }),
  F({
    id: "samma-ajiva",
    group: "magga",
    n: 5,
    pali: "sammā-ājīva",
    english: "Right livelihood",
    threads: ["sila"],
    phenomena: ["bhava"],
    sameAs: [],
    suttas: ["sn45_8", "mn141"],
    formula: "micchā-ājīvaṃ pahāya sammā-ājīvena jīvitaṃ kappeti",
    essence:
      "Abandoning wrong livelihood and living by a right one. For monastics, the allowances of the Vinaya; for laypeople, work that does not trade in harm.",
    practice: "Review how livelihood supports or undermines the other path factors.",
  }),
  F({
    id: "samma-vayama",
    group: "magga",
    n: 6,
    pali: "sammā-vāyāma",
    english: "Right effort",
    threads: ["viriya"],
    phenomena: ["nivarana", "lobha", "dosa", "moha"],
    sameAs: ["samvara", "pahana", "bhavana", "anurakkhana", "viriyindriya", "viriya-bala", "viriya-sambojjhanga", "viriya-iddhi"],
    suttas: ["sn45_8", "an4_14", "mn141"],
    formula: "chandaṃ janeti vāyamati viriyaṃ ārabhati cittaṃ paggaṇhāti padahati",
    essence:
      "The path-name of the four right strivings: prevent, abandon, develop, maintain. Effort that is neither slack nor strained.",
    practice: "Apply the four tasks to whatever state is present — hindrance or wholesome factor.",
  }),
  F({
    id: "samma-sati",
    group: "magga",
    n: 7,
    pali: "sammā-sati",
    english: "Right mindfulness",
    threads: ["sati"],
    phenomena: ["namarupa", "vedana", "khandha-set"],
    sameAs: ["kayanupassana", "vedananupassana", "cittanupassana", "dhammanupassana", "sati-sambojjhanga", "satindriya", "sati-bala"],
    suttas: ["sn45_8", "mn10", "dn22", "sn47_35"],
    formula: "kāye kāyānupassī … vedanāsu … citte … dhammesu dhammānupassī viharati, ātāpī sampajāno satimā",
    essence:
      "The four establishments of mindfulness as a path factor: ardent, clearly knowing, mindful, rid of longing and discontent.",
    practice: "Keep returning to body, feeling, mind, or dhammas without adding a story.",
  }),
  F({
    id: "samma-samadhi",
    group: "magga",
    n: 8,
    pali: "sammā-samādhi",
    english: "Right concentration",
    threads: ["samadhi", "samatha-vipassana"],
    phenomena: ["jhana", "nivarana", "nirodha"],
    sameAs: ["samadhi-sambojjhanga", "samadhindriya", "samadhi-bala"],
    suttas: ["sn45_8", "mn141", "sn56_11"],
    formula: "vivicceva kāmehi … paṭhamaṃ jhānaṃ … catutthaṃ jhānaṃ upasampajja viharati",
    essence:
      "Unification of mind. In the suttas this is typically the four jhānas, supported by the preceding seven factors.",
    practice: "Collect the mind on a wholesome object after virtue and effort have settled the hindrances.",
  }),
  F({
    id: "sati-sambojjhanga",
    group: "bojjhanga",
    n: 1,
    pali: "sati-sambojjhaṅga",
    english: "Mindfulness as awakening factor",
    threads: ["sati"],
    phenomena: ["nivarana", "namarupa"],
    sameAs: ["samma-sati", "satindriya", "sati-bala"],
    suttas: ["sn46_1", "sn46_51", "mn118"],
    formula: "satiṃ upaṭṭhapeti — sato ca kho bhikkhu dhammaṃ pajānāti",
    essence:
      "Mindfulness established so that dhammas can be seen. It both launches the other factors and keeps energizing and calming factors in balance.",
    practice: "When a hindrance or wholesome state appears, know it as it is, then feed the needed bojjhaṅga (SN 46.51).",
  }),
  F({
    id: "dhammavicaya",
    group: "bojjhanga",
    n: 2,
    pali: "dhammavicaya-sambojjhaṅga",
    english: "Investigation of dhammas",
    threads: ["panna", "samatha-vipassana"],
    phenomena: ["anicca", "khandha-set", "nivarana", "moha"],
    sameAs: ["samma-ditthi", "pannindriya", "panna-bala", "vimamsa"],
    suttas: ["sn46_51", "mn118", "mn77"],
    formula: "paññāya pavicinati pavicarati parivīmaṃsam āpajjati",
    essence:
      "Wise discrimination of states: wholesome and unwholesome, internal and external. This is paññā in the bojjhaṅga set.",
    practice: "Investigate: What is this? Is it skillful? What feeds it? What starves it?",
  }),
  F({
    id: "viriya-sambojjhanga",
    group: "bojjhanga",
    n: 3,
    pali: "viriya-sambojjhaṅga",
    english: "Energy as awakening factor",
    threads: ["viriya"],
    phenomena: ["nivarana"],
    sameAs: ["samma-vayama", "viriyindriya", "viriya-bala", "viriya-iddhi"],
    suttas: ["sn46_51", "mn118"],
    formula: "āraddhaviriyo viharati, asallīno",
    essence:
      "Aroused energy that does not collapse. Together with investigation and rapture it lifts a heavy mind.",
    practice: "When sloth or doubt is present, arouse energy; when restlessness is present, do not add more striving.",
  }),
  F({
    id: "piti",
    group: "bojjhanga",
    n: 4,
    pali: "pīti-sambojjhaṅga",
    english: "Rapture as awakening factor",
    threads: ["samatha-vipassana"],
    phenomena: ["jhana"],
    sameAs: [],
    suttas: ["sn46_51", "mn118"],
    formula: "pītimanassa kāyo passambhati",
    essence:
      "Joyful interest in the wholesome. It is an energizing factor and a jhāna factor; it leads on to tranquillity.",
    practice: "Gladden the mind by recalling virtue, generosity, or the Buddha — then let rapture quiet into calm.",
  }),
  F({
    id: "passaddhi",
    group: "bojjhanga",
    n: 5,
    pali: "passaddhi-sambojjhaṅga",
    english: "Tranquillity as awakening factor",
    threads: ["samadhi", "samatha-vipassana"],
    phenomena: ["jhana"],
    sameAs: [],
    suttas: ["sn46_51", "mn118"],
    formula: "passaddhakāyassa sukhino cittaṃ samādhiyati",
    essence:
      "Calming of body and mind. When the body is tranquil, the mind readily concentrates.",
    practice: "Soften extra effort after energy has done its work; feel the settling of the bodily formation.",
  }),
  F({
    id: "samadhi-sambojjhanga",
    group: "bojjhanga",
    n: 6,
    pali: "samādhi-sambojjhaṅga",
    english: "Concentration as awakening factor",
    threads: ["samadhi"],
    phenomena: ["jhana", "nivarana"],
    sameAs: ["samma-samadhi", "samadhindriya", "samadhi-bala"],
    suttas: ["sn46_51", "mn118"],
    formula: "samāhite citte yathābhūtaṃ pajānāti",
    essence:
      "A collected mind. From concentration, things are known as they are — the bridge into wisdom.",
    practice: "When the hindrances are thin, rest in one object until the mind is unified.",
  }),
  F({
    id: "upekkha",
    group: "bojjhanga",
    n: 7,
    pali: "upekkhā-sambojjhaṅga",
    english: "Equanimity as awakening factor",
    threads: ["samadhi", "samatha-vipassana"],
    phenomena: ["nirodha", "anicca"],
    sameAs: [],
    suttas: ["sn46_51", "mn118"],
    formula: "ajjhupekkhitā hoti",
    essence:
      "Looking-on with balance, not dull indifference. The mind that can stand in the middle without leaning on greed or hate.",
    practice: "When rapture and pleasure are strong, widen into evenness; know rise and fall without taking sides.",
  }),
  F({
    id: "saddhindriya",
    group: "indriya",
    n: 1,
    pali: "saddhindriya",
    english: "Faculty of faith",
    threads: ["saddha"],
    phenomena: ["micchaditthi"],
    sameAs: ["saddha-bala"],
    suttas: ["sn48_10", "sn48_43"],
    formula: "saddahati tathāgatassa bodhiṃ",
    essence:
      "Confidence that places the mind on the Tathāgata's awakening. It should be balanced with wisdom so it does not become mere belief.",
    practice: "Recollect Buddha, Dhamma, Saṅgha until the heart is willing to make effort.",
  }),
  F({
    id: "viriyindriya",
    group: "indriya",
    n: 2,
    pali: "viriyindriya",
    english: "Faculty of energy",
    threads: ["viriya"],
    phenomena: ["nivarana"],
    sameAs: ["viriya-bala", "samma-vayama", "viriya-sambojjhanga", "viriya-iddhi"],
    suttas: ["sn48_10", "an4_14"],
    formula: "āraddhaviriyo hoti akusalānaṃ dhammānaṃ pahānāya, kusalānaṃ dhammānaṃ upasampadāya",
    essence:
      "Energy as a governing faculty: the four strivings taking the lead in the mind.",
    practice: "Balance with concentration: more energy if the mind is slack, less if it is restless.",
  }),
  F({
    id: "satindriya",
    group: "indriya",
    n: 3,
    pali: "satindriya",
    english: "Faculty of mindfulness",
    threads: ["sati"],
    phenomena: ["namarupa"],
    sameAs: ["sati-bala", "samma-sati", "sati-sambojjhanga"],
    suttas: ["sn48_10", "mn10"],
    formula: "satimā hoti paramena satinepakkena samannāgato",
    essence:
      "Mindfulness as governor. In the five-faculty set it stands in the middle, balancing faith/wisdom and energy/concentration.",
    practice: "Use sati to notice which pair of faculties is overgrown and which is weak.",
  }),
  F({
    id: "samadhindriya",
    group: "indriya",
    n: 4,
    pali: "samādhindriya",
    english: "Faculty of concentration",
    threads: ["samadhi"],
    phenomena: ["jhana", "nivarana"],
    sameAs: ["samadhi-bala", "samma-samadhi", "samadhi-sambojjhanga"],
    suttas: ["sn48_10", "sn45_8"],
    formula: "vossaggārammaṇaṃ karitvā labhati samādhiṃ",
    essence:
      "The capacity to unify the mind, often described as obtaining concentration by making release the object.",
    practice: "Give the mind one wholesome home and return whenever it wanders.",
  }),
  F({
    id: "pannindriya",
    group: "indriya",
    n: 5,
    pali: "paññindriya",
    english: "Faculty of wisdom",
    threads: ["panna"],
    phenomena: ["anicca", "anatta", "avijja"],
    sameAs: ["panna-bala", "samma-ditthi", "dhammavicaya", "vimamsa"],
    suttas: ["sn48_10", "sn56_11"],
    formula: "ariyāya paññāya samannāgato udayatthagāminiyā",
    essence:
      "Noble wisdom that sees rise and fall. It balances faith and completes the faculties.",
    practice: "Look at the arising and ceasing of whatever sati is holding.",
  }),
  F({
    id: "saddha-bala",
    group: "bala",
    n: 1,
    pali: "saddhā-bala",
    english: "Power of faith",
    threads: ["saddha"],
    phenomena: ["micchaditthi"],
    sameAs: ["saddhindriya"],
    suttas: ["an5_2", "sn50_1", "sn48_43"],
    formula: "saddhā-balaṃ — na ca saddhāya kenaci kukkuccaṃ āpajjati",
    essence:
      "Faith that cannot be overthrown by disbelief. AN 5.2 connects its fulfilment with the four factors of stream-entry.",
    practice: "When doubt arises, return to what has already been verified in your own training.",
  }),
  F({
    id: "viriya-bala",
    group: "bala",
    n: 2,
    pali: "viriya-bala",
    english: "Power of energy",
    threads: ["viriya"],
    phenomena: ["nivarana"],
    sameAs: ["viriyindriya", "samma-vayama", "viriya-sambojjhanga", "viriya-iddhi"],
    suttas: ["an5_2", "sn50_1"],
    formula: "viriyaṃ bhāveti — kosajjaṃ nābhibhavati",
    essence:
      "Energy as a power is not overcome by laziness. Its fulfilment is the four right strivings.",
    practice: "Keep a steady daily effort rather than bursts that collapse.",
  }),
  F({
    id: "sati-bala",
    group: "bala",
    n: 3,
    pali: "sati-bala",
    english: "Power of mindfulness",
    threads: ["sati"],
    phenomena: ["namarupa"],
    sameAs: ["satindriya", "samma-sati", "sati-sambojjhanga"],
    suttas: ["an5_2", "sn50_1", "mn10"],
    formula: "sati-balaṃ — muṭṭhasaccaṃ nābhibhavati",
    essence:
      "Mindfulness that forgetfulness cannot overthrow. Its fulfilment is the four satipaṭṭhāna.",
    practice: "Treat lapses as a signal to re-establish, not as a verdict.",
  }),
  F({
    id: "samadhi-bala",
    group: "bala",
    n: 4,
    pali: "samādhi-bala",
    english: "Power of concentration",
    threads: ["samadhi"],
    phenomena: ["jhana", "nivarana"],
    sameAs: ["samadhindriya", "samma-samadhi", "samadhi-sambojjhanga"],
    suttas: ["an5_2", "sn50_1"],
    formula: "samādhi-balaṃ — uddhaccaṃ nābhibhavati",
    essence:
      "Concentration that restlessness cannot overthrow. Its fulfilment is the four jhānas.",
    practice: "Protect collectedness by simplifying inputs after the mind has settled.",
  }),
  F({
    id: "panna-bala",
    group: "bala",
    n: 5,
    pali: "paññā-bala",
    english: "Power of wisdom",
    threads: ["panna"],
    phenomena: ["avijja", "anicca", "anatta"],
    sameAs: ["pannindriya", "samma-ditthi", "dhammavicaya", "vimamsa"],
    suttas: ["an5_2", "sn50_1", "sn56_11"],
    formula: "paññā-balaṃ — avijjaṃ nābhibhavati",
    essence:
      "Wisdom that ignorance cannot overthrow. Its fulfilment is understanding the four noble truths.",
    practice: "Test views against rise-and-fall; keep what matches experience.",
  }),
  F({
    id: "kayanupassana",
    group: "satipatthana",
    n: 1,
    pali: "kāyānupassanā",
    english: "Contemplation of the body",
    threads: ["sati"],
    phenomena: ["rupa", "namarupa", "jaramarana", "salayatana"],
    sameAs: ["samma-sati"],
    suttas: ["mn10", "dn22", "mn118", "sn47_1"],
    formula: "kāye kāyānupassī viharati ātāpī sampajāno satimā",
    essence:
      "Breath, postures, clear knowing of activities, anatomical parts, elements, and cemetery contemplations. Seeing the body as body, not as self.",
    practice: "Anchor in the breath or posture, then know the body as elements and change.",
  }),
  F({
    id: "vedananupassana",
    group: "satipatthana",
    n: 2,
    pali: "vedanānupassanā",
    english: "Contemplation of feeling",
    threads: ["sati"],
    phenomena: ["vedana", "vedana-khandha", "tanha", "phassa"],
    sameAs: ["samma-sati"],
    suttas: ["mn10", "dn22", "mn118"],
    formula: "vedanāsu vedanānupassī viharati",
    essence:
      "Pleasant, painful, and neither-painful-nor-pleasant feelings, worldly and unworldly. Feeling is the hinge between contact and craving.",
    practice: "Label feeling-tone before liking or disliking builds a story.",
  }),
  F({
    id: "cittanupassana",
    group: "satipatthana",
    n: 3,
    pali: "cittānupassanā",
    english: "Contemplation of mind",
    threads: ["sati"],
    phenomena: ["vinnana", "vinnana-khandha", "anatta", "nivarana"],
    sameAs: ["samma-sati", "citta"],
    suttas: ["mn10", "dn22", "mn118"],
    formula: "citte cittānupassī viharati — sarāgaṃ vā cittaṃ ‘sarāgaṃ cittaṃ’ ti pajānāti",
    essence:
      "Knowing mind with lust or without, with hate or without, contracted, exalted, concentrated, released, and so on. Mind is seen as a changing process.",
    practice: "Ask: what is the mind like right now? Name it, do not become it.",
  }),
  F({
    id: "dhammanupassana",
    group: "satipatthana",
    n: 4,
    pali: "dhammānupassanā",
    english: "Contemplation of dhammas",
    threads: ["sati", "panna", "samatha-vipassana"],
    phenomena: ["nivarana", "khandha-set", "dukkha", "anicca", "anatta"],
    sameAs: ["samma-sati", "dhammavicaya"],
    suttas: ["mn10", "dn22", "mn118"],
    formula: "dhammesu dhammānupassī viharati — nīvaraṇesu, khandhesu, bojjhaṅgesu, saccesu",
    essence:
      "Mindfulness of mental principles: hindrances, aggregates, sense bases, awakening factors, and the four truths. This is sati working as wisdom.",
    practice: "When a hindrance or bojjhaṅga is present, know it, know its nutriment, and know its fading.",
  }),
  F({
    id: "samvara",
    group: "padhana",
    n: 1,
    pali: "saṃvara-padhāna",
    english: "Striving to prevent",
    threads: ["viriya", "sila"],
    phenomena: ["nivarana", "lobha", "dosa", "moha"],
    sameAs: ["samma-vayama"],
    suttas: ["an4_14", "sn49_1", "sn45_8"],
    formula: "anuppannānaṃ pāpakānaṃ akusalānaṃ dhammānaṃ anuppādāya chandaṃ janeti",
    essence:
      "Generating desire, effort, energy, and exertion so that unarisen unwholesome states do not arise. Sense restraint is the usual application.",
    practice: "Guard the doors: notice the first spark of a hindrance and do not feed it.",
  }),
  F({
    id: "pahana",
    group: "padhana",
    n: 2,
    pali: "pahāna-padhāna",
    english: "Striving to abandon",
    threads: ["viriya"],
    phenomena: ["nivarana", "tanha", "lobha", "dosa", "moha", "samudaya"],
    sameAs: ["samma-vayama"],
    suttas: ["an4_14", "sn49_1", "sn45_8"],
    formula: "uppannānaṃ pāpakānaṃ akusalānaṃ dhammānaṃ pahānāya chandaṃ janeti",
    essence:
      "Abandoning unwholesome states that have already arisen — by replacement, by seeing danger, or by cutting off at the root.",
    practice: "When greed, hate, or a hindrance is present, apply the appropriate antidote and do not continue the story.",
  }),
  F({
    id: "bhavana",
    group: "padhana",
    n: 3,
    pali: "bhāvanā-padhāna",
    english: "Striving to develop",
    threads: ["viriya", "samatha-vipassana"],
    phenomena: ["magga-sacca"],
    sameAs: ["samma-vayama"],
    suttas: ["an4_14", "sn49_1", "mn118"],
    formula: "anuppannānaṃ kusalānaṃ dhammānaṃ uppādāya chandaṃ janeti",
    essence:
      "Arousing wholesome states that have not yet arisen — especially the seven bojjhaṅga and the path factors.",
    practice: "Deliberately bring up sati, investigation, or a jhāna factor that is missing.",
  }),
  F({
    id: "anurakkhana",
    group: "padhana",
    n: 4,
    pali: "anurakkhaṇā-padhāna",
    english: "Striving to maintain",
    threads: ["viriya", "samadhi"],
    phenomena: ["jhana"],
    sameAs: ["samma-vayama"],
    suttas: ["an4_14", "sn49_1"],
    formula: "uppannānaṃ kusalānaṃ dhammānaṃ ṭhitiyā asammosāya bhiyyobhāvāya vepullāya bhāvanāya pāripūriyā",
    essence:
      "Maintaining arisen wholesome states so they do not decline, and bringing them to fulfilment.",
    practice: "When a wholesome mind is present, protect the conditions that keep it — posture, seclusion, and wise attention.",
  }),
  F({
    id: "chanda",
    group: "iddhipada",
    n: 1,
    pali: "chanda-iddhipāda",
    english: "Desire as a base of power",
    threads: ["samadhi"],
    phenomena: ["sankhara", "tanha"],
    sameAs: [],
    suttas: ["sn51_20", "sn51_15", "an4_276"],
    formula: "chanda-samādhi-padhāna-saṅkhāra-samannāgataṃ iddhipādaṃ bhāveti",
    essence:
      "Wholesome zeal for the goal, gathering into concentration, accompanied by the formations of striving. SN 51.15: this desire is for abandoning craving, and it subsides when the work is done.",
    practice: "Want the path itself more than the bait of the hindrances; let that wish collect the mind.",
  }),
  F({
    id: "viriya-iddhi",
    group: "iddhipada",
    n: 2,
    pali: "viriya-iddhipāda",
    english: "Energy as a base of power",
    threads: ["viriya", "samadhi"],
    phenomena: ["nivarana"],
    sameAs: ["samma-vayama", "viriyindriya", "viriya-bala", "viriya-sambojjhanga"],
    suttas: ["sn51_20", "an4_276"],
    formula: "viriya-samādhi-padhāna-saṅkhāra-samannāgataṃ iddhipādaṃ bhāveti",
    essence:
      "Energy that has become concentration-with-striving. Effort is not scattered; it is the vehicle of unification.",
    practice: "Apply energy to one object until the mind stays without being pushed.",
  }),
  F({
    id: "citta",
    group: "iddhipada",
    n: 3,
    pali: "citta-iddhipāda",
    english: "Mind as a base of power",
    threads: ["samadhi", "sati"],
    phenomena: ["vinnana", "vinnana-khandha"],
    sameAs: ["cittanupassana"],
    suttas: ["sn51_20", "an4_276"],
    formula: "citta-samādhi-padhāna-saṅkhāra-samannāgataṃ iddhipādaṃ bhāveti",
    essence:
      "The mind itself as the basis: a thoroughly applied citta that has gathered into samādhi with striving.",
    practice: "Take the knowing mind as home — not the content it is knowing.",
  }),
  F({
    id: "vimamsa",
    group: "iddhipada",
    n: 4,
    pali: "vīmaṃsā-iddhipāda",
    english: "Investigation as a base of power",
    threads: ["panna", "samadhi", "samatha-vipassana"],
    phenomena: ["anicca", "avijja"],
    sameAs: ["dhammavicaya", "pannindriya", "panna-bala", "samma-ditthi"],
    suttas: ["sn51_20", "an4_276"],
    formula: "vīmaṃsā-samādhi-padhāna-saṅkhāra-samannāgataṃ iddhipādaṃ bhāveti",
    essence:
      "Investigation that has become concentration-with-striving. Wisdom here is not dry thought; it is inquiry that unifies the mind.",
    practice: "Examine the object until interest and collectedness meet — then see rise and fall.",
  }),
];

export const PHENOMENON_KINDS = {
  nidana: "Dependent origination",
  khandha: "Aggregates",
  sacca: "Noble truths",
  lakkhana: "Characteristics",
  root: "Unwholesome roots",
  dhamma: "Training dhammas",
  "path-opposite": "Path opposites",
};

export function groupById(id) {
  return GROUPS.find((g) => g.id === id);
}

export function factorById(id) {
  return FACTORS.find((f) => f.id === id);
}

export function phenomenonById(id) {
  return PHENOMENA.find((p) => p.id === id);
}

export function suttaById(id) {
  return SUTTAS[id];
}

export function factorsInGroup(groupId) {
  return FACTORS.filter((f) => f.group === groupId).sort((a, b) => a.n - b.n);
}

export function relatedFactors(factor) {
  const ids = new Set(factor.sameAs || []);
  for (const other of FACTORS) {
    if (other.id === factor.id) continue;
    const shared = (other.threads || []).some((t) => (factor.threads || []).includes(t));
    if (shared && other.group !== factor.group) ids.add(other.id);
  }
  return [...ids].map(factorById).filter(Boolean);
}

export function factorsForThread(threadId) {
  return FACTORS.filter((f) => (f.threads || []).includes(threadId));
}

export function factorsForPhenomenon(phenomenonId) {
  const direct = FACTORS.filter((f) => (f.phenomena || []).includes(phenomenonId));
  const reverse = (phenomenonById(phenomenonId)?.factors || []).map(factorById).filter(Boolean);
  const map = new Map();
  for (const f of [...direct, ...reverse]) map.set(f.id, f);
  return [...map.values()];
}

function fieldScore(parts, q) {
  const text = parts.filter(Boolean).join(" ").toLowerCase();
  if (!text) return 0;
  if (text === q) return 4;
  const tokens = text.split(/[^\p{L}\p{N}]+/u).filter(Boolean);
  if (tokens.includes(q)) return 3;
  if (tokens.some((t) => t.startsWith(q))) return 2;
  if (q.length >= 5 && text.includes(q)) return 1;
  return 0;
}

export function searchCatalog(query) {
  const q = query.trim().toLowerCase();
  if (!q) return { groups: [], factors: [], phenomena: [], suttas: [], threads: [] };
  const rank = (items, fields) =>
    items
      .map((item) => ({ item, score: fieldScore(fields(item), q) }))
      .filter((row) => row.score > 0)
      .sort((a, b) => b.score - a.score)
      .map((row) => row.item);

  return {
    groups: rank(GROUPS, (g) => [g.english, g.pali, g.short, g.gloss, String(g.n)]),
    factors: rank(FACTORS, (f) => [f.english, f.pali, f.essence, f.practice]),
    phenomena: rank(PHENOMENA, (p) => [p.english, p.pali, p.essence, p.kind]),
    suttas: rank(Object.values(SUTTAS), (s) => [s.ref, s.title, s.pali, s.note]),
    threads: rank(THREADS, (t) => [t.english, t.pali, t.essence]),
  };
}

export function totalsOk() {
  const byGroup = Object.fromEntries(GROUPS.map((g) => [g.id, factorsInGroup(g.id).length]));
  const sum = FACTORS.length;
  return { sum, byGroup, expected: { magga: 8, bojjhanga: 7, indriya: 5, bala: 5, satipatthana: 4, padhana: 4, iddhipada: 4 } };
}
